-- =====================================================================
--  INFORMATIKA TEST TIZIMI  -  2-QADAM: savollar va o'quvchilar
--  01_setup.sql muvaffaqiyatli ishlagandan KEYIN shu faylni ishga tushiring.
--  Faylda parollar yo'q, faqat ularning shifrlangan (bcrypt) ko'rinishi bor.
--  Qayta ishga tushirish xavfsiz: o'quvchilar va natijalar o'chmaydi,
--  savollar matni esa yangilanadi.
-- =====================================================================

insert into public.app_tests(grade, is_open, duration_minutes) values (9,true,0),(10,true,0),(11,true,0) on conflict (grade) do nothing;

-- SAVOLLAR (to'g'ri javob 0 dan boshlab variant tartibi bilan berilgan)
-- 9-sinf: 45 ta savol
insert into public.app_questions(grade, num, question, options, correct) values
(9,1,'Quyidagilardan qaysi biri ma’lumot kiritish qurilmasi hisoblanadi?','["Printer", "Skanner", "Monitor", "Zummer"]'::jsonb,1),
(9,2,'Qaysi qurilma yordamida sensorli ekranda kursor harakatlantiriladi?','["Manipulyator", "Klaviatura", "Sensor panel", "Printer"]'::jsonb,2),
(9,3,'Qaysi qurilma orqali tasvirlar va hujjatlar raqamlashtiriladi?','["Mikrofon", "Monitor", "Skaner", "Printer"]'::jsonb,2),
(9,4,'Qaysi kiritish qurilmasi inson tomonidan to‘g‘ridan-to‘g‘ri ma’lumot kiritishni talab etmaydi?','["Joystik", "Shtrix-kod o‘qish qurilmasi", "Klaviatura", "Pult"]'::jsonb,1),
(9,5,'Raqamli kameraning afzalliklaridan biri nima?','["Suratni qog‘ozga chop etish", "Suratni darhol ko‘rish va o‘chirish", "Shtrix-kodni o‘qish", "Videoni kompyuterga yuklash"]'::jsonb,1),
(9,6,'Ma''lumotni chiqarish qurilmasini tanlang:','["Klaviatura", "Sichqoncha", "Displey ekrani", "Skaner"]'::jsonb,2),
(9,7,'Qaysi qurilma yordamida kompyuterdan chop etish amalga oshiriladi?','["Monitor", "Displey ekrani", "Skaner", "Printer"]'::jsonb,3),
(9,8,'Kompyuterda ma''lumotlarni chiqish sifatida audio qayd qilish uchun qaysi qurilma qo‘llaniladi?','["Karnay", "Skaner", "Klaviatura", "Printer"]'::jsonb,0),
(9,9,'OMR (Optical Mark Recognition) nima?','["Kompyuterdan chop etuvchi printer turi", "Ovozni yozib oluvchi qurilma", "Qog‘ozdagi belgilarni (masalan, test javob varaqlaridagi katakchalarni) optik usulda aniqlash texnologiyasi", "Magnit siyohli belgilarni aniqlash texnologiyasi"]'::jsonb,2),
(9,10,'Joystik qaysi sohada keng foydalaniladi?','["O‘yinlar", "Tibbiyot", "Dasturlash", "Matn kiritish"]'::jsonb,0),
(9,11,'Qaysi monitor turi TFT monitoridan kichikroq va yengilroq hisoblanadi?','["CRT", "IPS/LCD", "TFT", "Purkagichli printer"]'::jsonb,1),
(9,12,'Qaysi kiritish qurilmasi asosan bosma belgilarni raqamli shaklga aylantirish uchun qo‘llaniladi?','["Manipulyator", "Klaviatura", "Skaner", "MICR"]'::jsonb,2),
(9,13,'MICR texnologiyasi qaysi sohada qo‘llaniladi?','["Bank ishi", "O‘yinlar", "Veb-sayt yaratish", "Grafik dizayn"]'::jsonb,0),
(9,14,'RFID nima uchun qo‘llaniladi?','["To‘lqinli chastotani aniqlash", "Kredit kartalarni o‘qish", "Ma’lumotlarni qayta ishlash", "Sensorli ekranlarni boshqarish"]'::jsonb,0),
(9,15,'Chiqarish qurilmasi sifatida qaysi qurilmadan foydalaniladi?','["Monitor", "Klaviatura", "Joystik", "Sensor"]'::jsonb,0),
(9,16,'Xotira qurilmasi nima?','["Kompyuterning ma''lumotlarini saqlash va o''qish qurilmasi", "Ma''lumotlarni doimiy saqlaydigan optik disk", "Magnitli ma''lumotlar yozish qurilmasi", "Faqat RAM xotira bilan bog''liq qurilma"]'::jsonb,0),
(9,17,'Magnitli ma''lumot tashuvchilar qanday ishlaydi?','["Lazer yordamida ma''lumotlarni kuydirib yozadi", "Magnit qutblanishini o''zgartirish orqali ma''lumot saqlaydi", "Optik chiziqlar yordamida ma''lumotlarni yozadi", "Elektr energiyasini talab qiluvchi qurilmalar"]'::jsonb,1),
(9,18,'Qaysi qurilma optik ma''lumot tashuvchi hisoblanadi?','["USB fleshka", "SD karta", "CD RW disk", "Qattiq disk"]'::jsonb,2),
(9,19,'Magnitli xotira qurilmasining kamchiligi nima?','["Juda kichik hajmli ma''lumotlarni saqlaydi", "Ma''lumotlarga kirish tezligi past", "Xavfsizlik darajasi past bo''lishi mumkin", "Ma''lumotlarni faqat bir marta yozish mumkin"]'::jsonb,2),
(9,20,'Optik ma''lumot tashuvchilarda ma''lumotlar qanday saqlanadi?','["Qattiq disklarda magnitlangan holda", "Lazer yordamida yaratilgan chuqurchalar orqali", "Faqat RAM xotirada", "USB ulagich orqali"]'::jsonb,1),
(9,21,'Qattiq holatdagi ma''lumot tashuvchilarning afzalliklaridan biri nima?','["Ular harakatlanuvchi qismlarga ega", "Ular juda tez kirish imkonini beradi", "Juda katta hajmdagi ma''lumotlarni saqlay olmaydi", "Ular faqat elektr energiyasi bilan ishlaydi"]'::jsonb,1),
(9,22,'CD RW disklar qanday ma''lumot tashuvchi hisoblanadi?','["Faqat ma''lumotlarni o''qiy oladi", "Ma''lumotlarni yozish va o''chirish mumkin", "Ma''lumotlarni faqat bir marta yozish mumkin", "Harakatlanuvchi qismlarga ega"]'::jsonb,1),
(9,23,'Portativ qattiq disklardan foydalanishning afzalligi nima?','["Faqat kompyuter ichida foydalaniladi", "Tashqi quvvat manbaisiz ishlaydi", "Ma''lumotlar faqat bir martalik yoziladi", "Ma''lumotlarni faqat internet orqali o''tkazadi"]'::jsonb,1),
(9,24,'Magnit tasmali diskovodda ma''lumotlar qanday usulda saqlanadi?','["Ma''lumotlar ketma-ket usulda saqlanadi", "Ma''lumotlarga darhol kirish imkoniyati mavjud", "Foydalanish uchun internet talab qiladi", "Faqat kichik hajmdagi fayllar saqlanadi"]'::jsonb,0),
(9,25,'DVD RW disklar qanday turdagi ma''lumot tashuvchi hisoblanadi?','["Faqat ma''lumotlarni o''qiy oladi", "Faqat bir martalik yozish imkonini beradi", "Ko''p marta yozish va o''chirish mumkin", "Faqat musiqa fayllari uchun mos"]'::jsonb,2),
(9,26,'Qaysi turdagi xotira portativ va mustahkam hisoblanadi?','["CD ROM", "DVD RW", "USB fleshka", "Magnit tasma"]'::jsonb,2),
(9,27,'Ma''lumotlarni ketma-ket saqlash usulining (masalan, magnit tasmada) asosiy xususiyati qanday?','["Ma''lumotlarga tez kirish imkonini yaratadi", "Har qanday ma''lumotga bevosita (to''g''ridan-to''g''ri) murojaat qilish imkonini beradi", "Har bir ma''lumotni ketma-ket o''qishni talab qiladi", "Ma''lumotlarni faqat bir marta yozish imkonini beradi"]'::jsonb,2),
(9,28,'Qattiq holatdagi xotira qurilmalarining asosiy kamchiligi nima?','["Foydalanish juda qiyin", "Qimmat va xizmat muddati qisqa", "Juda ko''p energiya talab qiladi", "Faqat bitta kompyuterda ishlatiladi"]'::jsonb,1),
(9,29,'Qaysi xotira qurilmasi kompyuterdagi dasturlar va operatsion tizimni saqlash uchun ishlatiladi?','["Optik disk", "Qattiq disk", "SD karta", "USB fleshka"]'::jsonb,1),
(9,30,'Blu-ray disklari qanday maqsadda ishlatiladi?','["Faqat ma''lumotlarni zaxiralash uchun", "Kichik hajmdagi fayllarni saqlash uchun", "Yuqori sifatli videolarni saqlash uchun", "Faqat musiqa fayllarini yozish uchun"]'::jsonb,2),
(9,31,'LAN tarmog''i qaysi joylarda keng qo''llaniladi?','["Xalqaro korxonalarda", "Shahar tarmoqlarida", "Uy, maktab, ofislarda", "Radiostansiyalarda"]'::jsonb,2),
(9,32,'WAN tarmog''i qanday hududlarni qamrab oladi?','["Faqat bitta binoni", "Mahalliy joylarni", "Katta geografik hududlarni", "Faqat shaharlarni"]'::jsonb,2),
(9,33,'Routerning vazifasi nima?','["Fayllarni saqlash", "Ma''lumotlarni eng yaxshi yo''nalishda uzatish", "Kompyuterlarni ta''mirlash", "Tarmoq qurilmalari orasidagi signalni kuchaytirish"]'::jsonb,1),
(9,34,'Wi-Fi texnologiyasining asosiy afzalligi nima?','["Tezkor o''rnatilishi", "Faqat uy sharoitida ishlatilishi", "Kabel orqali tez ma''lumot uzatilishi", "Har qanday masofani qamrab olish"]'::jsonb,0),
(9,35,'Bluetooth texnologiyasining o''ziga xosligi nimada?','["Uzoq masofalarda ishlaydi", "Katta hajmdagi ma''lumotlarni uzatadi", "Kichik masofalarda qurilmalar orasida simsiz aloqa o''rnatadi", "Internetga ulanish tezligini oshiradi"]'::jsonb,2),
(9,36,'Modemning vazifasi nima?','["Ma''lumotni faqat saqlash va arxivlash", "Raqamli signalni analog signalga va analog signalni raqamli signalga aylantirish", "Faqat lokal tarmoqlarni boshqarish", "Ma''lumotni faqat Wi-Fi orqali uzatish"]'::jsonb,1),
(9,37,'Svichning asosiy funksiyasi nima?','["Xabarlarni kerakli qurilmaga yo''naltirish", "Xabarlarni barcha qurilmalarga bir vaqtning o''zida yuborish", "Tarmoqdagi har bir qurilmaga signal uzatish", "Ma''lumotlarni qayta ishlash"]'::jsonb,0),
(9,38,'Kompyuter tarmoqlari xavfsizligi nima uchun zarur?','["Internet tezligini oshirish uchun", "Tarmoqqa ruxsatsiz kirishni oldini olish uchun", "Qurilmalarning sonini ko''paytirish uchun", "Tarmoqda signalni kuchaytirish uchun"]'::jsonb,1),
(9,39,'WLAN tarmog''ining qaysi jihati to''g''ri?','["Faqat kabel orqali ishlaydi", "Qisqa masofalarda simsiz aloqa o''rnatadi", "Faqat ofislarda ishlatiladi", "Faqat bitta kompyuterga ulanadi"]'::jsonb,1),
(9,40,'Router ma''lumot paketini qanday saqlaydi?','["Ma''lumotni arxiv fayllarda saqlaydi", "Ma''lumotni yo''nalish jadvallarida saqlaydi", "Ma''lumotni kompyuter xotirasida saqlaydi", "Paketlarni serverga uzatadi"]'::jsonb,1),
(9,41,'Tarmoq interfeysi kartasi nima?','["Tarmoqdagi har bir kompyuterga tarmoqqa ulanish imkonini beruvchi qurilma", "Tarmoqda ma''lumotlar saqlash qurilmasi", "Internetga ulanish tezligini oshiruvchi qurilma", "Kompyuterlardagi dasturlarni boshqaruvchi tizim"]'::jsonb,0),
(9,42,'Intranet nima?','["Ma''lumotlarni saqlash uchun ishlatiladigan xotira qurilmasi", "Bitta tashkilot ichida ishlatiladigan yopiq (xususiy) tarmoq", "Butun dunyo bo''ylab ishlatiladigan tarmoq", "Simsiz tarmoq texnologiyasi"]'::jsonb,1),
(9,43,'Modem qanday ishlaydi?','["Ma''lumotni raqamli signaldan analog signalga o''zgartiradi", "Faqat tarmoq interfeysi kartalari bilan ishlaydi", "Wi-Fi signallarini uzatadi", "Faqat LAN tarmoqlarini boshqaradi"]'::jsonb,0),
(9,44,'Tarmoq xavfsizligini ta''minlash uchun qanday usullar qo''llaniladi?','["Parol va shifrlash", "Signalni kuchaytirish", "Ko''proq kompyuter qo''shish", "Faqat simli tarmoqlardan foydalanish"]'::jsonb,0),
(9,45,'Faks va elektron pochta o''rtasidagi asosiy farq nima?','["Faksda ma''lumotlarni filtrlash mumkin", "Faksda viruslar bo''lmaydi", "Elektron pochta qimmat", "Elektron pochta faqat ichki tarmoqlarda ishlaydi"]'::jsonb,1)
on conflict (grade, num) do update set question = excluded.question, options = excluded.options, correct = excluded.correct;

-- 10-sinf: 40 ta savol
insert into public.app_questions(grade, num, question, options, correct) values
(10,1,'Axborotlar qanday shakllarda uzatilishi mumkin?','["Matnli, raqamli.", "Ovozli, grafik.", "Barcha javob to`g`ri."]'::jsonb,2),
(10,2,'Ma`lumotlar turi bu - ……… .','["O`zgaruvchi yoki doimiy qiymatlardagi ma`lumotlar shakli.", "Kompyuterda berilgan ma`lumotlar.", "Dasturlash tili haqida beriladigan ma`lumotlar."]'::jsonb,0),
(10,3,'O`zgaruvchi qabul qilgan qiymat turini qaysi funksiya yordamida aniqlash mumkin?','["input().", "type().", "str()."]'::jsonb,1),
(10,4,'” //” ushbu arifmetik amal nomi?','["Bo`lish.", "Bo`linmaning qoldig`ini hisoblash.", "Bo`linmaning butun qiymatini hisoblash."]'::jsonb,2),
(10,5,'Satr nima?','["So`zlar ketma-ketligi.", "Harf, son va belgilar hamda probeldan tarkib topgan belgilar ketma-ketligi.", "To`g`ri javob yo`q."]'::jsonb,1),
(10,6,'Satr uzunligini qaysi funksiya yordamida aniqlash mumkin?','["len().", "Print()", "input()."]'::jsonb,0),
(10,7,'Satrlarni birlashtirish uchun qaysi amal qo`llaniladi?','["+", "-", "/"]'::jsonb,0),
(10,8,'Pythonda satrdagi belgilarni raqamlash nechchidan boshlanadi?','["1 dan", "0 dan", "2 dan"]'::jsonb,1),
(10,9,'Print() qanday vazifa bajaradi?','["Satr uzunligini aniqlaydi.", "Satrlarni birlashtiradi.", "Ma`lumotlarni ekranga chiqarish faylga yozish vazifasini bajaradi."]'::jsonb,2),
(10,10,'End va sep print nima uchun qo`llaniladi?','["Ma`lumotlarni chiqarish parametrlarini o`zgartirish uchun.", "Python dasturiga ma`lumotlarni yozish uchun.", "To`g`ri javob yo`q."]'::jsonb,0),
(10,11,'Dasturlash jarayonida asosan necha xil algoritmdan foydalaniladi?','["2 xil", "3 xil", "5 xil"]'::jsonb,1),
(10,12,'Buyruqlarning qat`iy ketma-ketlikda tartib bilan bajarilishi nima deb ataladi?','["Algoritm.", "Dasturlash jarayoni.", "Chiziqli algoritm."]'::jsonb,2),
(10,13,'Chiziqli algoritmlarni dastur shaklida yozilishiga ………… deyiladi.','["Chiziqli dastur.", "Chiziqli algoritm.", "To`g`ri javob yo`q."]'::jsonb,0),
(10,14,'Amallarning qat`iy ketma-ketlikda bajarilishi nima deb ataladi?','["Chiziqli dastur.", "Chiziqli ijro.", "Chiziqli algoritm."]'::jsonb,2),
(10,15,'O`zgaruvchilarni taqqoslash uchun qanday amallardan foydalaniladi?','["Sodda amallardan.", "Mantiqiy amallardan.", "To`g`ri javob yo`q."]'::jsonb,1),
(10,16,'Taqqoslash amallariga qaysi amallar kiradi?','["<,>,=,!=.", "<,=,+,-.", ">,+,=."]'::jsonb,0),
(10,17,'Birorta shartga ko`ra buyruqlar ketma-ketligining bajarilishi yoki bajarilmasligini belgilovchi algoritm nima deb ataladi?','["Dasturlash algoritmi.", "Tekshiruvchi algoritm.", "Tarmoqlanuvchi algoritm."]'::jsonb,2),
(10,18,'If operatori tarkibidagi shart True qiymat qaytarsa, buyruqlar bloki bajariladimi?','["yo`q.", "Ha.", "Bajarilmaydi."]'::jsonb,1),
(10,19,'Buyruqlar_bloki if operatoridan keyingi satrda xat boshidan nechta probel qoldirib keyin yoziladi?','["4 ta.", "8 ta.", "probel qoldirmay yoziladi."]'::jsonb,0),
(10,20,'Shartni tekshirish uchun qaysi operatordan foydalaniladi?','["Print().", "if.", "To`g`ri javob yo`q."]'::jsonb,1),
(10,21,'Shartdan kelib chiqib, har bir shartga mos buyruqlar ketma-ketligini bajaradigan ifning takomillashgan ko`rinishi……..?','["Elif operatori.", "If operatori.", "CASE operatori."]'::jsonb,0),
(10,22,'Elif-else va if so`zlarining kombinatsiyasi bo`lib, qanday ma`noni anglatadi?','["“Aks holda agar”", "“Rost  va yolg`on”", "To`g`ri javob yo`q."]'::jsonb,0),
(10,23,'Dastur tuzish jarayonida murakkab shartli ifodalarni yozish uchun nimalardan foydalaniladi?','["operatorlardan.", "Mantiqiy amallardan.", "Barcha javob to`g`ri."]'::jsonb,1),
(10,24,'“==” belgining nomi?','["Teng emas.", "Katta yoki teng.", "Aynan teng."]'::jsonb,2),
(10,25,'“\t  belgining nomi nima?','["Tabulyatsiya belgisi.", "Yangi satrga o`tish belgisi.", "bittalik qo`shtirnoq belgisi."]'::jsonb,0),
(10,26,'Chiziqli tuzilishga ega bo`lgan algoritmning blok-sxemasi asosan nimalar yordamida tuziladi?','["Algoritmni boshlash, tugatish bloki.", "Kiritish/chiqarish bloki, funksional bloki.", "Barcha javob to`g`ri."]'::jsonb,2),
(10,27,'…………. Bir chiziq bo`ylab joylashgan, ketma-ket bajariladigan ko`rsatmalar to`plami ko`rinishida bo`ladi.','["Chiziqli algoritm", "Chiziqli tuzilish", "To`g`ri javob yo`q."]'::jsonb,1),
(10,28,'Hozirgi kunda qanday dasturlash tillari keng tarqalgan?','["Pascal, Delphi, C, C++.", "Java, Python.", "Barcha javob to`g`ri."]'::jsonb,2),
(10,29,'Tarmoqlanuvchi struktura odatda qandaydir mantiqiy shartni ………… o`z ichiga oladi?','["Tekshirish blokini", "Tarmoqlanuvchi tuzilish.", "To`g`ri javob yo`q."]'::jsonb,0),
(10,30,'Biror bir shart tekshirilishi yoki qandaydir parametrning har xil qiymatlari asosida algoritmda takrorlanishi yuz beradigan jarayonlarga …………. .','["Tarmoqlanuvchi algoritm.", "Takrorlanuvchi algoritm.", "Tekshiriluvchi algoritm."]'::jsonb,1),
(10,31,'Hisoblash jarayonining ko`p marta takrorlanadigan qismi nima deb yuritiladi?','["SUMM.", "PRODUCT.", "Ichki sikl tanasi."]'::jsonb,2),
(10,32,'Tarkibida bir necha turdagi algoritmlar qatnashgan algoritmga ………….. deyiladi.','["Aralash algoritm", "Tarmoqlanuvchi algoritm.", "Tekshiruvchi algoritm."]'::jsonb,0),
(10,33,'Kompyuter uchun dastur tuzish jarayoni nima deyiladi?','["Kompyuter dasturi.", "Dasturlash.", "Dasturchi."]'::jsonb,1),
(10,34,'Kompyuterda biror masalani hal qilish uchun eng avvalo nima qilinadi?','["Kompyuterga yoziladi.", "Dastur tuziladi.", "Modeli va algoritmi tuziladi."]'::jsonb,2),
(10,35,'Yaratilgan matn kompyuter tilida nima deb ataladi?','["Yozilgan dastur.", "Tuzilgan dastur.", "Algoritm."]'::jsonb,1),
(10,36,'Dastur tuzuvchi shaxs nima deb yuritiladi?','["Dasturchi.", "Foydalanuvchi.", "To`g`ri javob yo`q."]'::jsonb,0),
(10,37,'Kir yuvish mashinasi ham dasturlash asosida ishlaydimi?','["Yo`q.", "Ha.", "To`g`ri javob yo`q."]'::jsonb,1),
(10,38,'Kompyuter tushunadigan va muloqot olib boradigan “til” ……… deb ataladi.','["Dastur.", "Dasturlash tili.", "Dasturlash algoritmi."]'::jsonb,1),
(10,39,'Translyator nima?','["Dastur turi.", "Dasturchi nomi.", "Tarjimon tili."]'::jsonb,2),
(10,40,'IDE so`zining to`liq nomi?','["Integrated Development Environment.", "Integrated Development.", "To`g`ri javob yo`q."]'::jsonb,0)
on conflict (grade, num) do update set question = excluded.question, options = excluded.options, correct = excluded.correct;

-- 11-sinf: 40 ta savol
insert into public.app_questions(grade, num, question, options, correct) values
(11,1,'MOBTning kengaytirilgan shakli keltirilgan qatorni belgilang.','["Ma’lumotlar omborini boshqarish tizimlari", "Ma’lumotlarni oson boshqarish tizimi", "Ma’lumotlarni og’riqli bilish tili", "Ma’lumotlar va obyektlar bilan ishlash tizimi"]'::jsonb,0),
(11,2,'Ma’lumotlar ombori tuzishning asosiy usullari qaysilar?','["Ierarxik, tarmoq", "Ierarxik, relyatsion", "Ierarxik, tarmoq, relyatsion", "to’g’ri javob yo’q"]'::jsonb,2),
(11,3,'Ma’lumotlar omborining shajara usuli yana qanday yuritiladi?','["Tarmoq", "Relyatsion", "Ierarxik", "barcha javoblar to’g’ri"]'::jsonb,2),
(11,4,'Ma’lumotlar qaysi usuldan foydalanib olish mumkin?','["Tuzilmalashtirilgan va tuzilmalashtirilmagan", "tizimlashtirilgan va tizilmalashtirilgan", "model va algoritm", "to’g’ri javob yo’q"]'::jsonb,0),
(11,5,'Ma’lumotlar omborini boshqarish tizimlariga misol keltirilganlardan qaysi qator to’g’ri?','["MySQL, MS Access, OpenOffice.org Base, Cache, IMS, Firebird", "Word, Access, Excel va Front Page", "Power Point, Excel, MySQL va DreamWeaver", "Access, Front Page, Publisher va Paint"]'::jsonb,0),
(11,6,'MOBT nima?','["jadvallar bilan ishlash uchun mo’ljallangan dastur", "matnlar bilan ishlash uchun mo’ljallangan dastur tizimi", "ma’lumotlar omborini bilish tizimi", "foydalanuvchilar tomonidan MOni yaratish, to’ldirish va birgalikda qo’llash uchun mo’ljallangan dasturiy vositalar tizimi."]'::jsonb,3),
(11,7,'Access dasturining asosiy menyulari to’liq keltirilgan qatorni toping.','["файл, поля, главная, создание, внешние данные, работа с базами данных, таблица", "файл, поля, главная, работа с базами данных, таблица", "файл, поля, главная, создание, внешние данные", "файл, поля, главная, создание, внешние данные, работа с базами данных, таблица, окно, справка"]'::jsonb,0),
(11,8,'Таблицы, Запросы, Формы, Страницы, Отчёты va Макросlar Access uchun nima bo’lib hisoblanadi?','["asosiy menyular", "uskunalar paneli", "asosiy elementlari", "asosiy funksiyalar"]'::jsonb,2),
(11,9,'MS Access 2010dagi tasvirlanadigan maydon turlari necha xil bo’ladi?','["8", "10", "12", "15"]'::jsonb,1),
(11,10,'MS Accessning fayllar kengaytmasi qanday?','["*.exe", "*.bin", "*.pdf", "*.accdb"]'::jsonb,3),
(11,11,'Quyidagilardan qaysi biri obyektga mo’ljallangan dasturlash tili hisoblanadi?','["Turbo Pascal", "Delphi", "QBasic", "Assembler"]'::jsonb,1),
(11,12,'Ilovalar yana qanday nomlar bilan yuritiladi?','["texnik ta’minot", "amaliy dasturlar", "dasturiy ta’minot", "drayverlar"]'::jsonb,1),
(11,13,'Dastur matnini kompyuter tusunadigan mashina kodiga o’girib beruvchi qurilma nima deb ataladi?','["translyator", "shina", "visual dasturlash", "assembler"]'::jsonb,0),
(11,14,'Mikroprossesorning buyruqlari yana qanday yuritiladi?','["mashina kodi", "assembler", "operatsion tizim", "umumlashgan dasturlar"]'::jsonb,0),
(11,15,'Tuzilmaviy dasturlash tili to’g’ri keltirilgan qatorni toping.','["Turbo paskal", "Delphi", "Java", "C++"]'::jsonb,0),
(11,16,'Delphi nomi qaerdan olingan?','["Odamning ismi", "Faylasufning ismi", "Misrdagi ibodatxona nomi", "Yunonistondagi ibodatxona nomi"]'::jsonb,3),
(11,17,'Delphi dasturi interfeysi bo’limlari to’g’ri keltirilgan qatorni toping.','["Uskunalar paneli, obyektlar brauzeri, obyektlar inspektori, dastur kodi oynasi, sarlavha satri, obyektlar paneli, ilova oynasi", "Obyektlar inspektori, dastur kodi oynasi, sarlavha satri, obyektlar paneli, asosiy menyu, ilova oynasi", "Uskunalar paneli, obyektlar brauzeri, obyektlar inspektori, dastur kodi oynasi, sarlavha satri, obyektlar paneli, asosiy menyu, ilova oynasi", "to’g’ri javob yo’q"]'::jsonb,2),
(11,18,'Delphi dasturining asosiy menyusi necha bo’limdan iborat?','["9", "10", "11", "13"]'::jsonb,2),
(11,19,'Object TreeView punkti qaysi menyuda joylashgan?','["Project", "View", "Component", "Run"]'::jsonb,1),
(11,20,'Delphida yaratilgan ilovalar qanday nomlanadi?','["proyekt", "prezentatsiya", "slayd", "hujjat"]'::jsonb,0),
(11,21,'Ilovalarni saqlash usullari to’g’ri keltirilgan qatorni belgilang.','["save, save as…,save project as…, save all", "save", "save as…, save", "barcha javoblar to’g’ri"]'::jsonb,0),
(11,22,'Dasturni tuzib bo’lgach ilovani ishga tushirish uchun qaysi klavishni bosish lozim?','["Run", "F8", "F9", "Shift+"]'::jsonb,2),
(11,23,'Tugma Delphi dasturida qanday yuritiladi?','["Pusk", "Button", "Caption", "Cancel"]'::jsonb,1),
(11,24,'Agar dasturda matn belgisi belgilangan miqdordan oshsa bu haqdagi ma’lumotni chiqaruvchi oynani hosil qilish uchun qaysi tugma lozim bo’ladi?','["Button", "Caption", "ShowMessage", "to’g’ri javob yo’q"]'::jsonb,2),
(11,25,'Ilovaning birinchi oynasi qanday nomlanadi?','["forma", "dastur kodi", "ko’rinish", "ilovaning yuzi"]'::jsonb,0),
(11,26,'Ilovaning ikkinchi oynasi qanday nomlanadi?','["forma", "dastur kodi", "ko’rinish", "ilovaning yuzi"]'::jsonb,1),
(11,27,'Ilova oynasining kengligi qaysi xoss orqali o’zgartiriladi?','["Caption", "Form", "Width", "Run"]'::jsonb,2),
(11,28,'Butun son turidagi kattalikni matn satri turidagi kattalikka o’tkazilish uchun qaysi funksiyasidan foydalanamiz?','["IntToStr", "height", "width", "caption"]'::jsonb,0),
(11,29,'Height xossasi nima uchun qo’llaniladi?','["balandlik", "chapdan tekislash", "kenglik", "top"]'::jsonb,0),
(11,30,'Labelning asosiy xossasi qaysi?','["Form", "Button", "Caption", "Name"]'::jsonb,2),
(11,31,'CheckBox obyektining asosiy xossasi …','["Chechkround", "Checkhouse", "Checked", "Caption"]'::jsonb,2),
(11,32,'Pascal dasturida ko’p variantli tanlash operatori qaysi?','["Case", "Read", "If…Else…", "Write"]'::jsonb,0),
(11,33,'Delphi dasturida bir nechta variantdan faqat bittasini tanlash uchun qaysi obyekt ishlatiladi?','["Check", "RadioGroup", "Edit", "Project"]'::jsonb,1),
(11,34,'Items qanday tarjima qilinadi?','["loyiha", "mashina", "inspector", "variant"]'::jsonb,3),
(11,35,'Ustun atamasi Delphi dasturlash tilida qanday yuritiladi?','["Columns", "CheckBox", "Radiogroup", "to’g’ri javob yo’q"]'::jsonb,0),
(11,36,'Ro’yxat qutisi to’g’ri keltirilgan qatorni belgilang.','["CheckBox", "ListBox", "ComboBox", "OutBox"]'::jsonb,1),
(11,37,'Yashirin ro’yxat qutisi qaysi qatorda keltirilgan?','["CheckBox", "ListBox", "ComboBox", "OutBox"]'::jsonb,2),
(11,38,'Sonni kiritish maydonchasi keltirilgan qatorni belgilang.','["Column", "Items", "SpinEdit", "ComboBox"]'::jsonb,2),
(11,39,'Qiymat Delphi dasturlash tilida qanday yuritiladi?','["SpinEdit", "ListBox", "Value", "Samples"]'::jsonb,2),
(11,40,'Namuna Delphi dasturlash tilida qanday yuritiladi?','["SpinEdit", "ListBox", "Value", "Samples"]'::jsonb,3)
on conflict (grade, num) do update set question = excluded.question, options = excluded.options, correct = excluded.correct;

-- O'QITUVCHI
insert into public.app_users(username, password_hash, role, full_name) values ('oqituvchi','$2a$10$oP.5EXGxe3l/YBRRd62EaeO.49Wrr5zqM4coyOdWgmte8cxKHG53C','teacher','O''qituvchi') on conflict (username) do nothing;

-- O'QUVCHILAR
insert into public.app_users(username, password_hash, role, full_name, grade, class_name, grp) values
('abdisalikov.ramazan','$2a$10$cosoSlJqNbAHTGtWEFF9uOndbm5DONnn8XiyuQ84/O51VQftIPhWy','student','Abdisalikov Ramazan',9,'9-A',1),
('adenov.meyirjan','$2a$10$DGavJH4ZTInPtZpkvobh7eoUyQAUsIHSlFmQ8YWhU.oaeEAx6CN9.','student','Adenov Meyirjan',9,'9-A',1),
('aljanov.bekzod','$2a$10$JjjD1TR6EI1.aDJVqSs.u.VEJm1AUDkRcAje5sHg58AtwmTrgZoe6','student','Aljanov Bekzod',9,'9-A',1),
('aljanova.guliza','$2a$10$hJMVEwjYSytJiRZq16jXhOb9rLyxd.3to1tYHKaRCv/avSio2MgtW','student','Aljanova Guliza',9,'9-A',1),
('altinbekova.asiya','$2a$10$oDLsn1Z0ndoaTWv5B1eW/uEIwjBkUftrk/8iIg3O4PR5Hg3gzBfjm','student','Altinbekova Asiya',9,'9-A',1),
('aralbayeva.uljan','$2a$10$gfmPDG8g0Nb9rf76zt805..WP53jahuCNBhMFCj366Tongq6O40/q','student','Aralbayeva Uljan',9,'9-A',1),
('arginbayeva.araylim','$2a$10$ip64ZG4iRDFXhQc6qjPQXOMi.ijaAZNr8lfqLszU0OjmIBGOTb0B.','student','Arginbayeva Araylim',9,'9-A',1),
('aripbayev.asilxan','$2a$10$UK7f.xparYZYcH8K.DpDC.9o5EG0ug8eC0aL0.DCLLjbB60iGmBfe','student','Aripbayev Asilxan',9,'9-A',1),
('asxarov.akaris','$2a$10$kCAquZCTvyKiH/baVrp7ce6SaMDD1vDTbHcRRU/iYA3ruM2mCq2/6','student','Asxarov Akaris',9,'9-A',1),
('aydarova.malika','$2a$10$DJcOJXHX77dtA5EaEnLsjenBA/T.SEzLFl9Hcx7jcGYqHsMsjvxIi','student','Aydarova Malika',9,'9-A',1),
('azimov.kuanish','$2a$10$7bcBCE.8RJhs65D.trN7seE3DK5ObtNttyniUVfeCeQTZg7ixiyVK','student','Azimov Kuanish',9,'9-A',1),
('musaliyeva.janiya','$2a$10$8Y23iRSlJWBsYJ3c8sbiBuWKIuDIYkNOAPwQ6q9zPFfQZQEaChcfy','student','Musaliyeva Janiya',9,'9-A',2),
('namazov.nursultan','$2a$10$yVNWmCTt6o.qE1ympvvGAuLKi83rhJsjDI6EIFtx/tDpcKZb0XT3y','student','Namazov Nursultan',9,'9-A',2),
('namazova.asemay','$2a$10$yrmNTGxu1zE4WTSmF12fwefLotNnLPx771refy9kdblSEf9.a47wm','student','Namazova Asemay',9,'9-A',2),
('nuraliyev.eldar','$2a$10$tm/sX4CHmWth7TkwSSxELexbCZ9TfNYF8gkMPeHfahapzTNQIunAu','student','Nuraliyev Eldar',9,'9-A',2),
('sabirova.ayaulim','$2a$10$.w.LsnjiRNlYcEMg4zizbOdHK6QVXrKwR6.AoWUVU05yqn3cZHaoO','student','Sabirova Ayaulim',9,'9-A',2),
('satbaldyev.aqan','$2a$10$h8Zw0CO.tiZzi9vsBYv8cOj2eORBrP42nUUMP2.ZAo/CvyYrrOiFe','student','Satbaldyev Aqan',9,'9-A',2),
('shagatayev.asxat','$2a$10$L.PYT23tQAfRivxEiCGkzOcv/2oMvLV8RkQA9GA2GgmW8Yuwb8N1G','student','Shagatayev Asxat',9,'9-A',2),
('sherpolatova.arujan','$2a$10$VZAk4TGWdIl5ZSWtEE36vObdxRc5rxJ7SKbgFZ7Iipg8uu66FXRHi','student','Sherpolatova Arujan',9,'9-A',2),
('suyimbayev.nurasil','$2a$10$uR..GSUwGZGZFZ/idNWq8eVfqMgXP2gLKhyGUoeW69hZ7Zwq8Nxd.','student','Suyimbayev Nurasil',9,'9-A',2),
('tillabekov.nurbek','$2a$10$9dxr6gVYfE0dyC9SU19WzOi4/ZXCd0mViu4HQvw7h75s5Nkhnylxe','student','Tillabekov Nurbek',9,'9-A',2),
('turapbayeva.sandugash','$2a$10$QgRbOTpY0fR53zcUlOH.T.e1alwfwX20H8iIxIcvc0cA1hAAnr0VW','student','Turapbayeva Sandugash',9,'9-A',2),
('urisbayeva.asem','$2a$10$aoESecEBGObVKDE5NWop4.uxzpF/8R.gSqOB5/LnBFLzd.X6ss6Te','student','Urisbayeva Asem',9,'9-A',2),
('yergeshbayev.nurqanat','$2a$10$yfok8XGMJGt.Lj88bx6CNuD4SSCoalkDVysodcJzBX/CiDZ5o6aMi','student','Yergeshbayev Nurqanat',9,'9-A',2),
('yesirkepov.azadbek','$2a$10$xPnyatndKDqfaa4LmSqf8e3SxZ/JouU38PoPyh8riEIgEt5UySUKG','student','Yesirkepov Azadbek',9,'9-A',2),
('abdikadirova.arujan','$2a$10$jhK3li8C0dM565HdqcmXIeQZjEL.IvNi/y7hM2EipHryxvZRJRT92','student','Abdikadirova Arujan',9,'9-B',1),
('anarbayeva.aqmaral','$2a$10$re0kjFvwq19VQ0G8VWEzceCeBZqGYWmj1IYIIG13dfZpxMlibgXrm','student','Anarbayeva Aqmaral',9,'9-B',1),
('anarbekova.uljan','$2a$10$8XeReDwvnj2HpDZY.J5Rx.8OTroU/qjyfP1jVw6/Me6OhPSDzdUYS','student','Anarbekova Uljan',9,'9-B',1),
('anarkuleyva.sabina','$2a$10$3U53YC0cxtCsxGpeYie.ee/hGAED5A6H8MFnm51wn3yt/dyKwS2ey','student','Anarkuleyva Sabina',9,'9-B',1),
('anarkulova.jansaya','$2a$10$ta.H68Q6Z5pmHVY59ZGNE.ILbyS.CwouTlyjCagVFHr8xGjoY8ZbC','student','Anarkulova Jansaya',9,'9-B',1),
('anasov.bibaris','$2a$10$XDXuUdcNTucKGe/JeAO5au9IZ0.xsXt78wr7i6Xc2qTvoUepgTfxq','student','Anasov Bibaris',9,'9-B',1),
('djanbirov.yelbek','$2a$10$QwhC2o0gJYrmDH8sH88kAuGWAXz0CCfv3GmreLHPN38w5fnEA2HIi','student','Djanbirov Yelbek',9,'9-B',1),
('janibekov.meirjan','$2a$10$HCidDHsT.45FfQfdeo4r4OsGb4QXq6aF2ASn1ibJ3q0CnY/C5Mo36','student','Janibekov Meirjan',9,'9-B',1),
('joldibayev.maksat','$2a$10$oxbw1UbwqiVgSaTTTZr9/ejX8C3lgksVIMlEGppn3TAsrnO1pHqh2','student','Joldibayev Maksat',9,'9-B',1),
('kuanishbayev.qanat','$2a$10$FcJ19TvYOtICdksIUh6Tv.WOsF1CVMxqONGOB3QbrQQY7Nqlxj76a','student','Kuanishbayev Qanat',9,'9-B',1),
('nasirdinov.nurtas','$2a$10$WANuvcv11rykE.nq4mRTxect55GPtNeeDWV59X/NftdJCi3Occ4By','student','Nasirdinov Nurtas',9,'9-B',1),
('nurjanova.jasmina','$2a$10$Qu3eBg.CcMarxZQcA8zlYOL2MxtkEI.L3/Wq.W0x3Z0hUPPC3bjZy','student','Nurjanova Jasmina',9,'9-B',1),
('omarov.sayan','$2a$10$Bb3Odo8c7d1.gQDxg6iB0uE0erPCP5H/7kNuUXGw1AYNOZGJKKh1e','student','Omarov Sayan',9,'9-B',1),
('orazaliyeva.kumush','$2a$10$b5qI6RqI/ssPWgrKkX91lO62lxW9ff/D7b.qmfxvs991.GqTtKZrW','student','Orazaliyeva Kumush',9,'9-B',1),
('raximbayev.ayan','$2a$10$F0.xOTLIBHc8CWo2gPyKcOOU9VvqL.dioqRt5qqUjeug/qBt65s7a','student','Raximbayev Ayan',9,'9-B',2),
('raximbayeva.dariya','$2a$10$eqx7tG/ualdDvoXD4GbvguA1/JEDwF06UJpWdMS/JrcxK2hzlj/2u','student','Raximbayeva Dariya',9,'9-B',2),
('risbekova.nurgisa','$2a$10$vacPe0ykSrnUkgfaLiy3W.kSmHFp0CE9/xJHc0Vz/pJ4ia8SDqgce','student','Risbekova Nurg''isa',9,'9-B',2),
('sarsenaliyeva.janar','$2a$10$Bg.VSIFK6sOyrQaUuAllJuRONGIy9Cdk0ogTg1vm4alfKGffnTrpG','student','Sarsenaliyeva Janar',9,'9-B',2),
('satibaldiyeva.aysha','$2a$10$aYJ3mfRLVpXqdCWUqTT8geRTZcHft1tOCAOGwG7FFUoBJwselkUlm','student','Satibaldiyeva Aysha',9,'9-B',2),
('satibaldiyeva.xanzada','$2a$10$BEZKVEOFWhpCxoTe0HDS8O57Ml548tvpVbIH8B843.ZjosUMDSyJy','student','Satibaldiyeva Xanzada',9,'9-B',2),
('talipbayeva.malika','$2a$10$KqedIO0VQwMsChTqkksmQe454EN0zoHTocOzV.IRH3voP/U9SQa.i','student','Talipbayeva Malika',9,'9-B',2),
('tillabayev.azizbek','$2a$10$.sD5uV06slPK3VL4D.KuzO91RSVa.mGk.99PFhv2QvF0RXsKRxQYC','student','Tillabayev Azizbek',9,'9-B',2),
('tleuberdiyev.nurbolat','$2a$10$dux16CtrlzySRPQBFSL3w.dsu5jh6VexXmGH7XOTm56ZEv4R9O3z6','student','Tleuberdiyev Nurbolat',9,'9-B',2),
('toktabayeva.bekayim','$2a$10$mD2XYu3o.aoIcynu3yzPI.4ZSza3Glaqf7mTMXcy8FLSUyu4XmC2G','student','Toktabayeva Bek-Ayim',9,'9-B',2),
('toktamuratova.sayajan','$2a$10$emkFsSShyrpHr.frWQf6qOhmL2pE3/HBuRr0tFCtmAvsdcOzhYIMO','student','Toktamuratova Sayajan',9,'9-B',2),
('tuksanbayev.yerdaulet','$2a$10$Hkfoyn81Zao8epXuk2pP..otu7DSS4jO14.D8zDy0Ioi85zGi9Zcm','student','Tuksanbayev Yerdaulet',9,'9-B',2),
('turginov.maqsat','$2a$10$0vW//I0Knc2kmkU3nMb/9ObhCcO5YmNmV71B0u4/3bR4dE1Zatw6K','student','Turginov Maqsat',9,'9-B',2),
('urinbasarov.meyirbek','$2a$10$Q9kToC0Ea1svijcNpkwaGOeSQMdkIU2pIzPl1gLosIi7Zx2URm44.','student','Urinbasarov Meyirbek',9,'9-B',2),
('yermatova.simbat','$2a$10$D/cngS8lP/a0ufdz2OlEeuK/8uzy3cWsXaOq4YiXWEqkTdsXh3Cd6','student','Yermatova Simbat',9,'9-B',2),
('yesenaliyeva.asema','$2a$10$TuK7e69RoWRmngdE1qHniOggZvGpQoef4IZuUKA49NnyBNJwzWJ5u','student','Yesenaliyeva Asema',9,'9-B',2),
('yesengeldiyeva.ayida','$2a$10$gLzL.te7x3juTSmVnKsel.q.F//RMmmF65vw0ZWz3lVTlbgyttsFW','student','Yesengeldiyeva Ayida',9,'9-B',2),
('abdikadirov.ayat','$2a$10$K1vafzMyDq03Pa4ZGrp/KOCZTeYWGcA0oZ3BiknTYkkTp44.u509a','student','Abdikadirov Ayat',10,'10-A',1),
('abdirazakova.gulnaz','$2a$10$jIZb47Ht2bWPNUzCo1HmlOwg/YeWhqLeIZG96BYPQGambLsu9OsxG','student','Abdirazakova Gulnaz',10,'10-A',1),
('abdujanapov.nurtas','$2a$10$p47tY6nFgyVd8HT7hVUkLOAmFMZ1PuAoWsjG4iw1APQAA0J1Bdl5y','student','Abdujanapov Nurtas',10,'10-A',1),
('alimbekov.beyimbet','$2a$10$y3jAUoGX1oDzBPUcTiEhgOWOFfmsxfMkCFgT2fRw00J4AmuZ5.jvG','student','Alimbekov Beyimbet',10,'10-A',1),
('amantayev.ruslan','$2a$10$4eAcrk5oAa6SzQCvzbf/y.yTDvcYFJ/u38T/k4WYy.Pb.I1fSeh6q','student','Amantayev Ruslan',10,'10-A',1),
('anarkulova.fariza','$2a$10$k5ghAIV.gSuY2kgbeBqdkedQvQhZedRslNoXxjUsxmnstZH5boYoK','student','Anarkulova Fariza',10,'10-A',1),
('askarov.bekzat','$2a$10$BliMdE92vysm0oOsKmfQKOD5r2PENDysY0YZl6BHZ.RWbCkpFWZ7m','student','Askarov Bekzat',10,'10-A',1),
('baltabayev.nurqanat','$2a$10$dQPgZojX.r8QaRI8MSjhSuOZV5zQmJpQ3Z/kMso6XLuZLZIbCTcje','student','Baltabayev Nurqanat',10,'10-A',1),
('baxtyarova.sabrina','$2a$10$kYXYkLpJP/ObAKWDZtmJy.n60AxUVLWwzqtUaCe60blZln1x8JbVm','student','Baxtyarova Sabrina',10,'10-A',1),
('jamalbekov.azamat','$2a$10$XcfLVGs0DqsViAkBfl5UWOJ2gGqS.1kZv8aS6uj3YZ46bwdb9ElZi','student','Jamalbekov Azamat',10,'10-A',1),
('jarilkapova.umida','$2a$10$qq6cBlZF0lrUC9qIQRK9suqu21TkyxHAf5OGgju5piF99akG5.766','student','Jarilkapova Umida',10,'10-A',1),
('kadirbekova.nazerke','$2a$10$zG57RpccLo9pJ59tEsWw7uZ53E1lyasXABE5zoyQMtkrjoK2eUR5.','student','Kadirbekova Nazerke',10,'10-A',1),
('kaldibayeva.jayna','$2a$10$bCPpD2tSXnb052zvmv2abeYUni33QmifVsO2k/l2QPdD3ItjGj8j2','student','Kaldibayeva Jayna',10,'10-A',1),
('muxtarov.alisher','$2a$10$enxw0Yxw5XockblvdPHyz.P4MPhKe7BdYnZ0Q8IcHiMQMTlANDORa','student','Muxtarov Alisher',10,'10-A',2),
('orinbekov.nurdaulet','$2a$10$tZ1stTzLdsDgl4M28JBOwuV3uoO5xo8gkdD/XYtWp5I6B1Z.MZwxO','student','Orinbekov Nurdaulet',10,'10-A',2),
('razakova.roza','$2a$10$5w10ssxLI1LaQPQDlaQI8u4juMCXTWIJ5GImwxnoAglypqH62DTJK','student','Razakova Roza',10,'10-A',2),
('rejepov.asan','$2a$10$L1ew5Wt.TEAlrASn2P2cxOKbKP14JY8G63Gm3PxgtomAtxl1MVXdu','student','Rejepov Asan',10,'10-A',2),
('saparkulov.sayat','$2a$10$n7S89p7kV6rWBgJUju0GZ.gWNJljq0Kmt8MfcWDhjwnY0hIBaMRvO','student','Saparkulov Sayat',10,'10-A',2),
('satibaldyev.asilbek','$2a$10$M9NEW4vY9UfreJfiaEj.negr/WGho6z5gUAU/G0fzN6HceSDgW6CW','student','Satibaldyev Asilbek',10,'10-A',2),
('seytxanova.jasmina','$2a$10$ZmHKppX6IH15ODissgZCf.riVj9SgRLmhBFaYDZuQj2e9mhEL0vO2','student','Seytxanova Jasmina',10,'10-A',2),
('taubayeva.gulimxan','$2a$10$5iiZeu2nlr.nneaQASkB..G3mmGh1rCtz38xJU0PkJ4Ivmb.X05cG','student','Taubayeva Gulimxan',10,'10-A',2),
('temirbekov.bakitjan','$2a$10$soNukWsw5a71s.tyrZce9O52T8PdBUsL38wHGNHxeWt7D.yOnpCx6','student','Temirbekov Bakitjan',10,'10-A',2),
('tileuberdiev.erasil','$2a$10$Ys97DugTgPEfj26CxXhMbuV7F0R63G7.wh4nFARYLCsF0NLkvnmea','student','Tileuberdiev Erasil',10,'10-A',2),
('tuymekulov.alisher','$2a$10$piBlLrF.TWct/l5JytQ33OvydX/d8tKjfHRdfMrZVyRZ0n6eXrJqG','student','Tuymekulov Alisher',10,'10-A',2),
('ukibayeva.ulbosin','$2a$10$XBIG93D2opKMDxAg3Z2xhe6zinZ2U.bXV3gzYUfxlXvOZzRswocYm','student','Ukibayeva Ulbosin',10,'10-A',2),
('usenov.mamadali','$2a$10$D7BV9eitg0yemTPImkpYWeKHRGXC5HvGPiJTlLyvE1BpTuKVgkpDS','student','Usenov Mamadali',10,'10-A',2),
('zyamidinova.dana','$2a$10$U1WreSJp1pMGH33QmTLSIuVyue83msPFlPz/hfxy39xIFW7MYEqha','student','Zyamidinova Dana',10,'10-A',2),
('abdikalikova.adina','$2a$10$sWNZUoQxGD/mgnuWTAw7fuMIuDI5bB71yVha3q7BmT0MNnDcZsWvW','student','Abdikalikova Adina',10,'10-B',null),
('abdumalikov.bekzat','$2a$10$YI.4IhIk9O1DCw045CkWpe7DJ4B3t.ht4lqrfbmxfUMypR8ui9AnW','student','Abdumalikov Bekzat',10,'10-B',null),
('alibekov.bekzat','$2a$10$J2XB6.EDRqs9Pt.VWAcoPOYITjPeKEl1OfMKdJUuaDUybgz1AWTzq','student','Alibekov Bekzat',10,'10-B',null),
('aljanova.asiya','$2a$10$NyXxb4Ak2UJ/ys7T.VwXbe.OFLNbH9MHfL7Zam7N7kJFhoUpP2vPe','student','Aljanova Asiya',10,'10-B',null),
('alpbekov.erjigit','$2a$10$C5Ct1.ccV3NOH7cOEZOf6eBgMjkcmLONf7s14s0lshVYNJ/aL7MXa','student','Alpbekov Erjigit',10,'10-B',null),
('amangeldieva.ayaulim','$2a$10$eXFnT6v0cYsufctJip4u4u9zepDKBOJL2LxO9Atr4dYNG7BhOFCTi','student','Amangeldieva Ayaulim',10,'10-B',null),
('anarbayeva.aqmarjan','$2a$10$wdDIeCTgf3ENxZunMqlChO1RiAGPz8h6.VHFAl/eJhbZmCZJR07ES','student','Anarbayeva Aqmarjan',10,'10-B',null),
('arapbaev.nurmaxan','$2a$10$bGFUWUra0HL57Pj4ho9Bt.r1OE8kgDqxWOvjlxCXFNnvOZ7ecVMLS','student','Arapbaev Nurmaxan',10,'10-B',null),
('ashirbekova.asem','$2a$10$KUUYwOzp8fJ7VB.FNQDj8u7c0JnWZFV6YhJStJX7G4dNDtiaQA2by','student','Ashirbekova Asem',10,'10-B',null),
('bektaeva.janerke','$2a$10$SwCC93Zl3Q3J9Iv7Jf4jhOjQ7hKPE5lpcoL8YxrUYrLD2XK..Ocla','student','Bektaeva Janerke',10,'10-B',null),
('djakipov.elnur','$2a$10$LGiuV1RJV3X1AwTWgX7sM.4ZSSnOyBVy7AS1YDi0pUwtsu2dVj8t.','student','Djakipov Elnur',10,'10-B',null),
('janibekova.malika','$2a$10$GhIVIouAW2Xqu.38RUutpu9C8ZnJ5egIxOfov45nKT1VZXMpG2N/m','student','Janibekova Malika',10,'10-B',null),
('kumekova.elnura','$2a$10$GFYAzg6EPfOUdhoZ/H2vp.zQVk8TXWn3fqZcre5JAUC9N09ltt7WG','student','Kumekova Elnura',10,'10-B',null),
('muhtarov.damir','$2a$10$cwlwyGmJWQlmpOlhZDEIzOaLw4jrNYvpNkYDdWaXjMpClK9GxsVvW','student','Muhtarov Damir',10,'10-B',null),
('namazova.aselya','$2a$10$nsOhJuOaYYthAzA8wxeMvejlcvFj4TWHBwrDJn77jeK.jBxbmBsHC','student','Namazova Aselya',10,'10-B',null),
('narimbayeva.sabina','$2a$10$01iTVuAdkzqRYnU.fijn0.vkvfXokSnYO9BgsMWV7cd3Ov5eGxcoC','student','Narimbayeva Sabina',10,'10-B',null),
('sabitov.adilet','$2a$10$kx1eN8uqVuJmWSy5fWlBlOVMAUc1gXxQaPEC/FG89YPvM8H/fvRRO','student','Sabitov Adilet',10,'10-B',null),
('serikbayeva.arujan','$2a$10$fOVihNgrd2/U311M3qLjhuJofyJ0f8AFwbT4YTCM/tccMF6JLQTL2','student','Serikbayeva Arujan',10,'10-B',null),
('suyerova.asiya','$2a$10$/6lmd2PcyX/FZeKwqldu6ut3wJJl63ajVDHHic2kwO9VwIpeGa1bC','student','Suyerova Asiya',10,'10-B',null),
('tulepova.ayida','$2a$10$mqpMuVskhW6.HLcCMYLa0O0II41HrK8MPSgq3GZxb4SCnsNL9eK0.','student','Tulepova Ayida',10,'10-B',null),
('turginbayev.janseyit','$2a$10$gC7YHoSwDQh/.T1V50yuaeT8ygKojR0EO87MdjpU3W..Yoo7aEkK6','student','Turginbayev Janseyit',10,'10-B',null),
('xamitov.jasulan','$2a$10$rZ1ymWs4R6jJ/1dekTus4.cG0Oqu054tP5AQVqx1DCYBns6lJI1o2','student','Xamitov Jasulan',10,'10-B',null),
('abdikadirov.diyas','$2a$10$28lgYLDZxM7RlVmHulFaEeauT6PDqAKNVQ2sFtX.2qTqKh/OnP5rS','student','Abdikadirov Diyas',11,'11-A',1),
('abdikaxarova.saida','$2a$10$WsJ2TS49Qi5pArc8hp.eheFlHPdUnB/H8z3Caogt8aOj8qplOq6ae','student','Abdikaxarova Saida',11,'11-A',1),
('abdinabiyev.bekbolat','$2a$10$0yUA9aFJ/6kf7FSg4va8fOB5lFFXKA2XKAgy8jaNvgcWjDaH4yT96','student','Abdinabiyev Bekbolat',11,'11-A',1),
('albiyeva.uliza','$2a$10$LzF6XHm95xq0r.VscIb6R.HBH3EZIzxt501jkIliRs30iNPa7lf92','student','Albiyeva Uliza',11,'11-A',1),
('anarbayeva.alina','$2a$10$rXoVBRBcpDuDPsBp3yTsxe9nWAMvCzT0HUJ1XI7iuwYtGVbGUrLay','student','Anarbayeva Alina',11,'11-A',1),
('anarbekova.aqerke','$2a$10$599rFVE4.gVKyH396QWEWOHYA9DOT9tw3O0ml4kHYeSTI0VuMv1Sm','student','Anarbekova Aqerke',11,'11-A',1),
('anarkulyev.azimbek','$2a$10$APnzo2bSd4vFJq90SY2G3uzCFQ3N2rJO.H9mgYf41ww2TAFRqwYjC','student','Anarkulyev Azimbek',11,'11-A',1),
('bayzakov.aydos','$2a$10$MIuYU/DtmoAp4ZA2nup8LObpDs4iWaSaOyfXCvMPLHpr1sgN3Giyu','student','Bayzakov Aydos',11,'11-A',1),
('djanbirov.janarbek','$2a$10$Nc5UNwq7uAFxkcIJso20V.D9tlLQP6mIaNRnORupFCkgZrYiKP/Zi','student','Djanbirov Janarbek',11,'11-A',1),
('ibragimov.doston','$2a$10$ovc7pxn91vF3XbKEw69u/.u94RjuX4kPLS0M4/MFxUiZCI.L60dAO','student','Ibragimov Doston',11,'11-A',1),
('kadirkulov.beknur','$2a$10$XgGuszf2w6/miXL5nIVIbuT01USw3weow26wjQqCs22mrm1OEyrRC','student','Kadirkulov Beknur',11,'11-A',1),
('kamalov.berik','$2a$10$SZxzGysVX3HPUXp2BDZ5s.pJvtyKB0RnPTDpQDh02e7bxJOrT6ICK','student','Kamalov Berik',11,'11-A',1),
('kanatov.azat','$2a$10$CiqUgZWVQ22hYi39ftgI../UViflR6nTHtro91RK.AfARjqLtbLti','student','Kanatov Azat',11,'11-A',1),
('kenesbayev.nuran','$2a$10$5fXc04SDg6oT7PBeeWFT0.bJNMgI.MYU6J2kowKKckVjmhEgpqdD2','student','Kenesbayev Nuran',11,'11-A',1),
('kuandikova.sanjana','$2a$10$JJL5kr.4TXODjqYwSicsveb43IBvJG2D6haXL7ouZKB19N4lPwUzS','student','Kuandikova Sanjana',11,'11-A',1),
('kuralov.janbolat','$2a$10$vMD1kJsUUQ1BR5M9VMox3utHmh3JVxJ0B5OKZgdtlNvRyfE2TWktG','student','Kuralov Janbolat',11,'11-A',1),
('kurbanova.shinar','$2a$10$ee3zflE83qQnudNEpbJLjehK912aVA3Dh65swBaSxAznKbaV1gaiS','student','Kurbanova Shinar',11,'11-A',2),
('lesbekova.jannur','$2a$10$TBWhtJn3wUhngGtQd3cM3eW9WDmzHBAcaVSuz3uLZOrxE.CxchMoa','student','Lesbekova Jannur',11,'11-A',2),
('nasiridinova.moldir','$2a$10$mztCRoe0fyuDvgxNahrFsugc8hBQrTUOMTM4JUNgFB2WE8Z.2O6jC','student','Nasiridinova Moldir',11,'11-A',2),
('nurmaxanbetov.asadbek','$2a$10$D9IQps/B5NwrwO0MUmftze7v6G6x.v6Xtk8Er2ZNSqJk9Nzb8frNG','student','Nurmaxanbetov Asadbek',11,'11-A',2),
('omarova.diana','$2a$10$SWdgujhgKfTaWr0IKYzovuTIampFfxMJ7txQxQTLq.YTY/6nq30hW','student','Omarova Diana',11,'11-A',2),
('omirkulova.jansaya','$2a$10$5uv0kGLcR.NPN77atHdFkuyrKlVy5bEslzArBzFggsMwelU6C68NK','student','Omirkulova Jansaya',11,'11-A',2),
('omirzakov.bekjigit','$2a$10$IE4tbYDqX2qy7ivcdCAKreL6ZiBNRyyujFYbyvnMgd0GG9OxT4Hee','student','Omirzakov Bekjigit',11,'11-A',2),
('orazaliyev.yerlan','$2a$10$xDRGrUmziVmB9CHrxhIEeu9rGoPn17e6mexJTiMsVDOUEbjlY.HtS','student','Orazaliyev Yerlan',11,'11-A',2),
('ormanova.qarligash','$2a$10$kJ3y0VHJ2XjENZc6Evbrm.V/E18T4A/GC3wFFvwhrnV8L8ETD1O2y','student','Ormanova Qarlig''ash',11,'11-A',2),
('raximbayev.damir','$2a$10$mu9nE2yce0Aa.Wibf27ViupximEuGFEOenqtP8IYxfK2nLs6M88g2','student','Raximbayev Damir',11,'11-A',2),
('sadirbekov.maqsat','$2a$10$nXjbZPKGG6qq5nOUK6UT1OFQTdsCns0NnoFGaiLbgy5zuoLn27rAG','student','Sadirbekov Maqsat',11,'11-A',2),
('talipbayeva.bagnur','$2a$10$neUlDzW.GJXJwY0L4QGaTug9.u1LNwkVflB4NLBS8/eKjj7SLv8.2','student','Talipbayeva Bag''nur',11,'11-A',2),
('tastanbekov.sayat','$2a$10$G8TcvoptEUFLCM6Sq8a6Pev3Y4agFnRQyD6nHmEWqiip.F8j3nnBy','student','Tastanbekov Sayat',11,'11-A',2),
('tiliubaev.bek','$2a$10$VlyeHAoJeMwmDLgUxUYX3O5zpbBGmHZqvv0FL3YGia1NEWcSucoga','student','Tiliubaev Bek',11,'11-A',2),
('urinbasarov.aqjigit','$2a$10$C/BVEQVyJTmqZvtQDsx4cOiMmdnggNX48O20LYHJB2mP5CI9nqPBW','student','Urinbasarov Aqjigit',11,'11-A',2),
('urinbasarova.aydana','$2a$10$7orT.jgeLtzjoN9VphP/H.DAg6JBHhDYljKCA7s58BKQzNbIjrbSm','student','Urinbasarova Aydana',11,'11-A',2),
('abdiev.aqjigit','$2a$10$iPs2AWEMyoggVyutBtIUi.5MOrWSCnCsitWGepB4eXA2PIwl28PHG','student','Abdiev Aqjigit',11,'11-B',1),
('abdikanov.nurdos','$2a$10$4LlD9/TfAP5086rDPenbCuonYtfeKDrTja5UklKXLukWb9pQe/.Ae','student','Abdikanov Nurdos',11,'11-B',1),
('aripbaev.alixan','$2a$10$S2p8.ssjkJ7XJcaC4YPIFOUytAZrPEfk5bzO5speG7W6vO0lj5KL2','student','Aripbaev Alixan',11,'11-B',1),
('ashirbekov.ruslan','$2a$10$0D7CqYebYzOUhbRd5Q6.D.2nWLafBxfZTVjOSUIO3p6Fqe4883PJ.','student','Ashirbekov Ruslan',11,'11-B',1),
('bakirova.akjayik','$2a$10$i0.nmDPXz4o10eVw.2ka4e9wUJnzJV/tt0AE8riS3PVCJqGMkB2QO','student','Bakirova Akjayik',11,'11-B',1),
('bazarbaev.bekjigit','$2a$10$yQban2dA35zcoYOIu1b5Puijk86ebPliv.ujW.rC9adl5jAADLCMS','student','Bazarbaev Bekjigit',11,'11-B',1),
('boribekov.nurjas','$2a$10$bHSm49XKWRneYADdZRCVNeNquRkRfojBcheYg3.c.bYHgvthFlUF6','student','Boribekov Nurjas',11,'11-B',1),
('djanbirov.bagdaulet','$2a$10$LYweXEFbmEn.SotANuPYiOTztFSyrtLF1Fh4syiaGwt5BGi7yHiGq','student','Djanbirov Bagdaulet',11,'11-B',1),
('djapparova.gulzar','$2a$10$/sHSf5eHJiZIRzIFlq2WEejZsuTu917w2XY8LsaiJmVueGl/riiXK','student','Djapparova Gulzar',11,'11-B',1),
('ergeshbaev.xayat','$2a$10$bTDx0pbV/rL64pVyHmzZ/eCe.OtvECc9BLRPOLJ47ZByGp7IdYC36','student','Ergeshbaev Xayat',11,'11-B',1),
('ilyasov.abzal','$2a$10$0xfbQcJhTB6m2KvFgElZc.mNri46bpQzdU458/sfAr1Ajy42yJ85W','student','Ilyasov Abzal',11,'11-B',1),
('jarilqapova.diana','$2a$10$SBA.OMBSRRjnhyBA9eqf2edhM7Ex6dyNfhlMP.A1jSnxLqMxavFCe','student','Jarilqapova Diana',11,'11-B',1),
('joldibayev.rayimbek','$2a$10$Rqh4W4plFXBo1BUIAy/ez.JdtbCY4y5bL4B9N.khS/KB44johnhfu','student','Joldibayev Rayimbek',11,'11-B',1),
('jumabekov.janbolat','$2a$10$uHEkJ9uxLQfiGRV.hj3KC.RgS/8E1/GoRa4T138cMop0KvYVvQ7ru','student','Jumabekov Janbolat',11,'11-B',1),
('karjauova.aydana','$2a$10$ujvpAcFsGtWSZRXi725RheMLeLzIblsRMk1BVcVluSouUmTfqf5YG','student','Karjauova Aydana',11,'11-B',1),
('kasimkulova.ayken','$2a$10$WC2ZsX7Kcs1YWCTyXJFOFebmvn/hsKPtBkXa1Hh87bDpVLTmqJcei','student','Kasimkulova Ayken',11,'11-B',2),
('mamitova.ulmeken','$2a$10$lYZSxIQcXgYiMUWwDHClKO6nnPptVW/MKuxyBUmUEPJ/OePHmeRy2','student','Mamitova Ulmeken',11,'11-B',2),
('muratbekova.zarina','$2a$10$swIthZ.AKK2wSHeM78O2KugOTynYsJ2sXWJqCbuzwIhLW3RwGko0i','student','Muratbekova Zarina',11,'11-B',2),
('muratov.niyetjan','$2a$10$1OOtvkqmzaDqvZ6m.1ddhusejUG5pb1Vmro.dZoZCB1SwMWJNeG4y','student','Muratov Niyetjan',11,'11-B',2),
('musaev.dias','$2a$10$de1paujbxlT7TqiNd2RlLumLXXBPoi5EZMGowNwJSmn9HcRW.//w2','student','Musaev Dias',11,'11-B',2),
('muxtarov.elbek','$2a$10$e9PuZeSyikLD0ZjxhmczLOdwyTc4qFZrzQIRdkI.J3re4ji87EnoO','student','Muxtarov Elbek',11,'11-B',2),
('namazova.arujan','$2a$10$8Ej9qieZu.vv1X8F/UXBd.oaLjhFV7tpbISzhjYf1eCcl1NHVDl7W','student','Namazova Arujan',11,'11-B',2),
('nurbekov.nurtas','$2a$10$toHkqE..5DC7jkAbGbBaBOzADI1upuzO949Bid1wpQVqrRZgHknvm','student','Nurbekov Nurtas',11,'11-B',2),
('rejepova.arina','$2a$10$p.ZRHJpkOjV2Zo4FV38lB.9bwUU7TaGEcEelLHS7EIaCUtq/ewPbe','student','Rejepova Arina',11,'11-B',2),
('sandibaeva.asel','$2a$10$aHkNy4hwM2DQNrUI7LK.vOWGnyKEUsAhkgq6us1WI.AoFoeW2rcKy','student','Sandibaeva Asel',11,'11-B',2),
('sarsenbayeva.arujan','$2a$10$VeBgPvDeJntsvvjYQSIke.UV9hhmxQF3QPCG70C3lLvxYfUs4eAyu','student','Sarsenbayeva Arujan',11,'11-B',2),
('tagayov.nurbolat','$2a$10$dRuOQazFSjrxZj9iP9u9Eucy/4LlgY3CuAA2FwL2QQVvNGHzN1ZdC','student','Tagayov Nurbolat',11,'11-B',2),
('urusbayev.yerqanat','$2a$10$h8hGtnQdx1IcJ76JAOGT.OIj5WKdwSULvBhGFV.7Jqd2hHKsmjFJ.','student','Urusbayev Yerqanat',11,'11-B',2),
('uvalixanov.elnur','$2a$10$vhsOb6GeaPKp9M5PqwxceeTdgvn/sf52gRYvcforXSFcCyynLllSu','student','Uvalixanov Elnur',11,'11-B',2)
on conflict (username) do nothing;

select role, count(*) as soni from public.app_users group by role;
select grade, count(*) as savollar from public.app_questions group by grade order by grade;